---
title: "Statistical Analyses of TRex Movement Data"
author: "Hannah Anderson"
date: "2024-02-20"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


## Setup

```{r setup, include=FALSE}
setwd("C://Users/hande/Documents/R/fluctuating-turbidity2")
library(tidyverse)
library(glmmTMB)
library(emmeans)
library(car)
library(DHARMa)

#importing the data
clay_data <- read_csv("6day_clay_movement_data.csv")
dye_data <- read_csv("6day_dye_movement_data.csv")
#adding a column to identify the experiment
clay_data$experiment <- "clay"
dye_data$experiment <- "dye"

#changing tank IDs to shoal IDs to ensure IDs are different between experiments
clay_data <- clay_data %>%
             rename_at("tankID", ~"shoalID")
clay_data$shoalID <- gsub("tank", "clay", clay_data$shoalID)
dye_data <- dye_data %>%
            rename_at("tankID", ~"shoalID")
dye_data$shoalID <- gsub("tank", "dye", dye_data$shoalID)

#combining the clay and dye data together into a single data frame
comp_data <- rbind(clay_data, dye_data)
```


## Direct Comparison Models

```{r direct}
#sub-setting the data to only include recording 3
direct_data <- comp_data %>%
               filter(recording == "record3")

#mean speed
d_speed <- lm(mean_speed ~ treatment*experiment, data = direct_data)
#speed variance
d_var_speed <- update(d_speed, speed_variance ~ .)
#activity ratio
d_activ <- glmmTMB(activity_ratio ~ treatment*experiment, data = direct_data,
                   family = ordbeta(link = "logit"))
#total distance traveled
d_dist <- update(d_speed, totaldist_cm ~ .)
#maximum speed
d_mx_speed <- update(d_speed, max_speed ~ .)
#maximum acceleration
d_accel <- update(d_speed, max_acceleration ~ .)

#checking model assumptions
plot(simulateResiduals(fittedModel = d_speed))
plot(simulateResiduals(fittedModel = d_var_speed))
plot(simulateResiduals(fittedModel = d_activ))
plot(simulateResiduals(fittedModel = d_dist))
plot(simulateResiduals(fittedModel = d_mx_speed))
plot(simulateResiduals(fittedModel = d_accel))

#analyzing the results
Anova(d_speed)
Anova(d_var_speed)
Anova(d_activ)
Anova(d_dist)
Anova(d_mx_speed)
Anova(d_accel)
```


## Full Comparison Models

```{r full}
#averaging together together the two morning recordings for each measure and for
#each experiment
morn_data <- comp_data %>%
             filter(recording %in% c("record1", "record3")) %>%
             select(-recording) %>%
             group_by(shoalID, treatment, experiment) %>%
             summarize(mean_speed = mean(mean_speed),
                       activity_ratio = mean(activity_ratio),
                       speed_variance = mean(speed_variance),
                       max_speed = mean(max_speed),
                       max_acceleration = mean(max_acceleration),
                       totaldist_cm = mean(totaldist_cm))
#labeling these values as the morning values
morn_data$time <- "morning"
#averaging together the afternoon values
afte_data <- comp_data %>%
             filter(recording %in% c("record2", "record4")) %>%
             select(-recording) %>%
             group_by(shoalID, treatment, experiment) %>%
             summarize(mean_speed = mean(mean_speed),
                       activity_ratio = mean(activity_ratio),
                       speed_variance = mean(speed_variance),
                       max_speed = mean(max_speed),
                       max_acceleration = mean(max_acceleration),
                       totaldist_cm = mean(totaldist_cm))
afte_data$time <- "afternoon"
#combining the averaged morning and afternoon values into a single dataframe
full_data <- rbind(morn_data, afte_data)


#the statistical models

#mean speed
speed <- lm(mean_speed ~ treatment*experiment, data = full_data)
#speed variance
var_speed <- update(speed, speed_variance ~ .)
#activity ratio
activ <- glmmTMB(activity_ratio ~ treatment*experiment, data = full_data,
                   family = ordbeta(link = "logit"))
#total distance traveled
dist <- update(speed, totaldist_cm ~ .)
#maximum speed
mx_speed <- update(speed, max_speed ~ .)
#maximum acceleration
accel <- update(speed, max_acceleration ~ .)

#checking model assumptions
plot(simulateResiduals(fittedModel = speed))
plot(simulateResiduals(fittedModel = var_speed)) #doesn't meet assumptions
plot(simulateResiduals(fittedModel = activ))
plot(simulateResiduals(fittedModel = dist))
plot(simulateResiduals(fittedModel = mx_speed))
plot(simulateResiduals(fittedModel = accel))

#analyzing the results
Anova(speed)
#Anova(var_speed)
Anova(activ)
Anova(dist)
Anova(mx_speed)
Anova(accel)
```