---
title: "Movement Plots"
author: "Hannah Anderson"
date: "2024-01-29"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C://Users/hande/Documents/R/fluctuating-turbidity2")
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(ggpubr)

claydata <- read_csv("6day_clay_movement_data.csv")
dyedata <- read_csv("6day_dye_movement_data.csv")

#adding identifier for the value in the flux condition during each recording
claydata$flux_level <- claydata$recording %>%
                       fct_collapse(low = c("record1", "record3"),
                                    high = c("record2", "record4"))
dyedata$flux_level <- dyedata$recording %>%
                      fct_collapse(low = c("record1", "record3"),
                                   high = c("record2", "record4"))

#relabeling the "control" condition to "clear" condition for clarity
claydata$treatment <- recode(claydata$treatment, control = "clear")
dyedata$treatment <- recode(dyedata$treatment, control = "clear")
```

## Clay Plots

```{r clay, echo = FALSE}
#basic histogram plots to look at distributions combining all treatments and all
#recordings
hist_speed <- ggplot(claydata, aes(x = mean_speed, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Clay Experiment: Mean Speed",
                   subtitle = "All Speed Values") +
              xlab("Speed (cm/s)") + ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_maxspeed <- ggplot(claydata, aes(x = max_speed, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Clay Experiment: Max Speed",
                      subtitle = "All Max Speeds") +
                 xlab("Maximum Speed (cm/s)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_activ <- ggplot(claydata, aes(x = activity_ratio, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Clay Experiment: Activity",
                   subtitle = "All Activity Values") +
              xlab("Ratio of Seconds Spent Active to Total Time") +
              ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_maxaccel <- ggplot(claydata, aes(x = max_acceleration, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Clay Experiment: Max Acceleration",
                      subtitle = "All Max Acceleration Values") +
                 xlab("Maximum Acceleration (cm/s^2)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_dist <- ggplot(claydata, aes(x = totaldist_cm, fill = treatment)) +
             geom_histogram(position = "identity", alpha = 0.5) +
             labs(title = "Clay Experiment: Distance Traveled",
                  subtitle = "All Distance Values") +
             xlab("Total Distance Traveled (cm)") + ylab("Counts") +
             scale_fill_manual(values = c("blue", "red", "yellow")) +
             theme_classic()
hist_arrange <- ggarrange(hist_speed, hist_maxspeed, hist_activ,
                          hist_maxaccel, hist_dist, ncol = 3, nrow = 2)


#box plots across all treatments, including all recordings
box_speed <- claydata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = mean_speed, fill = treatment)) +
                geom_boxplot() +
                labs(title = "Clay Experiment: Mean Speed",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Mean Speed (cm/s)") +
                scale_fill_manual(values =
                                  c("slategray1", "wheat1", "wheat4")) +
                #ylim() +
                theme_classic()
box_maxspeed <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = treatment, y = max_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Max Speed",
                      subtitle = "Across all recordings") +
                 xlab("Treatments") + ylab("Maximum Speed (cm/s)") +
                 scale_fill_manual(values =
                                   c("slategray1", "wheat1", "wheat4")) +
                 #ylim() +
                 theme_classic()
box_activ <- claydata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = activity_ratio,
                           fill = treatment)) +
                geom_boxplot() +
                labs(title = "Clay Experiment: Activity",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Ratio of Seconds Spent Active to Total Time") +
                scale_fill_manual(values =
                                  c("slategray1", "wheat1", "wheat4")) +
                #ylim() +
                theme_classic()
box_maxaccel <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = max_acceleration,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Max Acceleration",
                   subtitle = "Across all recordings") +
              xlab("Treatments") +
              ylab("Maximum Acceleration (cm/s)") +
              scale_fill_manual(values =
                                c("slategray1", "wheat1", "wheat4")) +
              #ylim() +
              theme_classic()
box_dist <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = totaldist_cm, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Distance Traveled",
                   subtitle = "Across all recordings") +
              xlab("Treatments") + ylab("Total Distance Traveled (cm)") +
              scale_fill_manual(values =
                                c("slategray1", "wheat1", "wheat4")) +
              #ylim() +
              theme_classic()
box_arrange <- ggarrange(box_speed, box_maxspeed, box_activ,
                         box_maxaccel, box_dist, ncol = 3, nrow = 2)

#box plots across all treatments, separated by recording
time_speed <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = mean_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Mean Speed",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Mean Speed (cm/s)") + 
                 scale_fill_manual(values =
                                   c("slategray1", "wheat1", "wheat4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                 color = "gray", linewidth = 1.5) +
                 theme_classic()
time_maxspeed <- claydata %>%
                  mutate(treatment = fct_relevel(treatment,
                                                 "clear", "flux", "stable")) %>%
                  ggplot(aes(x = recording, y = max_speed, fill = treatment)) +
                  geom_boxplot() +
                  labs(title = "Clay Experiment: Max Speed",
                       subtitle = "All Data by Recording") +
                  xlab("Treatments") + ylab("Maximum Speed (cm/s)") + 
                  scale_fill_manual(values =
                                    c("slategray1", "wheat1", "wheat4")) +
                  geom_vline(xintercept = 2.5, linetype = "dashed",
                  color = "gray", linewidth = 1.5) +
                  theme_classic()
time_activ <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = activity_ratio,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Activity",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Ratio of Seconds Spent Active to Total Time") + 
                 scale_fill_manual(values =
                                   c("slategray1", "wheat1", "wheat4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                 color = "gray", linewidth = 1.5) +
                 theme_classic()
time_maxaccel <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = max_acceleration,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Max Acceleration",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") +
              ylab("Maximum Acceleration (cm/s^2)") + 
              scale_fill_manual(values =
                                c("slategray1", "wheat1", "wheat4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
              color = "gray", linewidth = 1.5) +
              theme_classic()
time_dist <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = totaldist_cm, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Distance Traveled",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") + ylab("Total Distance Traveled (cm)") + 
              scale_fill_manual(values = c("slategray1", "wheat1", "wheat4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
              color = "gray", linewidth = 1.5) +
              theme_classic()
time_arrange <- ggarrange(time_speed, time_maxspeed, time_activ,
                         time_maxaccel, time_dist, ncol = 3, nrow = 2)

#boxplots by what visibility level the flux condition was in during the
#recording (high or low)
hilo_speed <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = mean_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Mean Speed",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Mean Speed (cm/s)") +
                 scale_fill_manual(values = c("slategray1", "wheat1",
                                              "wheat4")) +
                 theme_classic()
hilo_maxspeed <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = max_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Max Speed",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Maximum Speed (cm/s)") +
                 scale_fill_manual(values = c("slategray1", "wheat1",
                                              "wheat4")) +
                 theme_classic()
hilo_activ <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = activity_ratio,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Activity",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Ratio of Seconds Spent Active to Total Time") +
                 scale_fill_manual(values = c("slategray1", "wheat1",
                                              "wheat4")) +
                 theme_classic()
hilo_maxaccel <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = max_acceleration,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Max Acceleration",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") +
              ylab("Maximum Acceleration (cm/s^2)") +
              scale_fill_manual(values = c("slategray1", "wheat1", "wheat4")) +
              theme_classic()
hilo_dist <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = totaldist_cm, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Distance Traveled",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") + ylab("Total Distance Traveled (cm)") +
              scale_fill_manual(values = c("slategray1", "wheat1", "wheat4")) +
              theme_classic()
hilo_arrange <- ggarrange(hilo_speed, hilo_maxspeed, hilo_activ,
                         hilo_maxaccel, hilo_dist, ncol = 3, nrow = 2)
```


## Dye Plots

```{r dye, echo = FALSE}
#basic histogram plots to look at distributions combining all treatments and all
#recordings
hist_speed <- ggplot(dyedata, aes(x = mean_speed, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Dye Experiment: Mean Speed",
                   subtitle = "All Speed Values") +
              xlab("Speed (cm/s)") + ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_maxspeed <- ggplot(dyedata, aes(x = max_speed, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Dye Experiment: Max Speed",
                      subtitle = "All Max Speeds") +
                 xlab("Maximum Speed (cm/s)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_activ <- ggplot(dyedata, aes(x = activity_ratio, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Dye Experiment: Activity",
                   subtitle = "All Activity Values") +
              xlab("Ratio of Seconds Spent Active to Total Time") +
              ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_maxaccel <- ggplot(dyedata, aes(x = max_acceleration, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Dye Experiment: Max Acceleration",
                      subtitle = "All Max Acceleration Values") +
                 xlab("Maximum Acceleration (cm/s^2)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_dist <- ggplot(dyedata, aes(x = totaldist_cm, fill = treatment)) +
             geom_histogram(position = "identity", alpha = 0.5) +
             labs(title = "Dye Experiment: Distance Traveled",
                  subtitle = "All Distance Values") +
             xlab("Total Distance Traveled (cm)") + ylab("Counts") +
             scale_fill_manual(values = c("blue", "red", "yellow")) +
             theme_classic()
hist_arrange <- ggarrange(hist_speed, hist_maxspeed, hist_activ,
                          hist_maxaccel, hist_dist, ncol = 3, nrow = 2)


#box plots across all treatments, including all recordings
box_speed <- dyedata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = mean_speed, fill = treatment)) +
                geom_boxplot() +
                labs(title = "Dye Experiment: Mean Speed",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Mean Speed (cm/s)") +
                scale_fill_manual(values =
                                  c("slategray1", "snow3", "snow4")) +
                #ylim() +
                theme_classic()
box_maxspeed <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = treatment, y = max_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Max Speed",
                      subtitle = "Across all recordings") +
                 xlab("Treatments") + ylab("Maximum Speed (cm/s)") +
                 scale_fill_manual(values =
                                   c("slategray1", "snow3", "snow4")) +
                 #ylim() +
                 theme_classic()
box_activ <- dyedata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = activity_ratio,
                           fill = treatment)) +
                geom_boxplot() +
                labs(title = "Dye Experiment: Activity",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Ratio of Seconds Spent Active to Total Time") +
                scale_fill_manual(values =
                                  c("slategray1", "snow3", "snow4")) +
                #ylim() +
                theme_classic()
box_maxaccel <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = max_acceleration,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Max Acceleration",
                   subtitle = "Across all recordings") +
              xlab("Treatments") +
              ylab("Maximum Acceleration (cm/s)") +
              scale_fill_manual(values =
                                c("slategray1", "snow3", "snow4")) +
              #ylim() +
              theme_classic()
box_dist <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = totaldist_cm, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Distance Traveled",
                   subtitle = "Across all recordings") +
              xlab("Treatments") + ylab("Total Distance Traveled (cm)") +
              scale_fill_manual(values =
                                c("slategray1", "snow3", "snow4")) +
              #ylim() +
              theme_classic()
box_arrange <- ggarrange(box_speed, box_maxspeed, box_activ,
                         box_maxaccel, box_dist, ncol = 3, nrow = 2)

#box plots across all treatments, separated by recording
time_speed <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = mean_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Mean Speed",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Mean Speed (cm/s)") + 
                 scale_fill_manual(values =
                                   c("slategray1", "snow3", "snow4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                 color = "gray", linewidth = 1.5) +
                 theme_classic()
time_maxspeed <- dyedata %>%
                  mutate(treatment = fct_relevel(treatment,
                                                 "clear", "flux", "stable")) %>%
                  ggplot(aes(x = recording, y = max_speed, fill = treatment)) +
                  geom_boxplot() +
                  labs(title = "Dye Experiment: Max Speed",
                       subtitle = "All Data by Recording") +
                  xlab("Treatments") + ylab("Maximum Speed (cm/s)") + 
                  scale_fill_manual(values =
                                    c("slategray1", "snow3", "snow4")) +
                  geom_vline(xintercept = 2.5, linetype = "dashed",
                  color = "gray", linewidth = 1.5) +
                  theme_classic()
time_activ <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = activity_ratio,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Activity",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Ratio of Seconds Spent Active to Total Time") + 
                 scale_fill_manual(values =
                                   c("slategray1", "snow3", "snow4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                 color = "gray", linewidth = 1.5) +
                 theme_classic()
time_maxaccel <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = max_acceleration,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Max Acceleration",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") +
              ylab("Maximum Acceleration (cm/s^2)") + 
              scale_fill_manual(values =
                                c("slategray1", "snow3", "snow4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
              color = "gray", linewidth = 1.5) +
              theme_classic()
time_dist <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = totaldist_cm, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Distance Traveled",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") + ylab("Total Distance Traveled (cm)") + 
              scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
              color = "gray", linewidth = 1.5) +
              theme_classic()
time_arrange <- ggarrange(time_speed, time_maxspeed, time_activ,
                         time_maxaccel, time_dist, ncol = 3, nrow = 2)

####the below colors are almost certainly not going to work properly
#boxplots by what visibility level the flux condition was in during the
#recording (high or low)
hilo_speed <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = mean_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Mean Speed",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Mean Speed (cm/s)") +
                 scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
                 theme_classic()
hilo_maxspeed <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = max_speed, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Max Speed",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Maximum Speed (cm/s)") +
                 scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
                 theme_classic()
hilo_activ <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = activity_ratio,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Activity",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Ratio of Seconds Spent Active to Total Time") +
                 scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
                 theme_classic()
hilo_maxaccel <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = max_acceleration,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Max Acceleration",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") +
              ylab("Maximum Acceleration (cm/s^2)") +
              scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
              theme_classic()
hilo_dist <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = totaldist_cm, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Distance Traveled",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") + ylab("Total Distance Traveled (cm)") +
              scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
              theme_classic()
hilo_arrange <- ggarrange(hilo_speed, hilo_maxspeed, hilo_activ,
                         hilo_maxaccel, hilo_dist, ncol = 3, nrow = 2)
```