---
title: "Proximity and Space Use Plots"
author: "Hannah Anderson"
date: "2024-01-19"
output: pdf_document
---

## Setup

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C://Users/hande/Documents/R/fluctuating-turbidity2")
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(ggpubr)

claydata <- read_csv("6day_clay_proximity_data.csv")
dyedata <- read_csv("6day_dye_proximity_data.csv")

#adding identifier for the value in the flux condition during each recording
claydata$flux_level <- claydata$recording %>%
                       fct_collapse(low = c("record1", "record3"),
                                    high = c("record2", "record4"))
dyedata$flux_level <- dyedata$recording %>%
                      fct_collapse(low = c("record1", "record3"),
                                   high = c("record2", "record4"))

#relabeling the "control" condition to "clear" condition for clarity
claydata$treatment <- dplyr::recode(claydata$treatment, control = "clear")
dyedata$treatment <- dplyr::recode(dyedata$treatment, control = "clear")

#combining the data into a single dataframe to include both experiments in the
#same figures
claydata$experiment <- "clay"
dyedata$experiment <- "dye"
combodata <- rbind(claydata, dyedata)
```


## Clay Plots

```{r clay, echo = FALSE}
#basic histogram plots to look at distributions combining all treatments and all
#recordings
hist_polarity <- ggplot(claydata, aes(x = polarity, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Clay Experiment: Polarity",
                      subtitle = "All Polarity Values") +
                 xlab("Polarity (1-circular variance)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_neighbor <- ggplot(claydata, aes(x = mean_neighbor, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Clay Experiment: Mean Neighbor Distances",
                      subtitle = "All Mean Neighbor Distances") +
                 xlab("Mean Neighbor Distance (cm)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_shoal <- ggplot(claydata, aes(x = shoal_area, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Clay Experiment: Shoal Area",
                   subtitle = "All Shoal Area Values") +
              xlab("Area of Shoal (cm^2)") + ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_wall <- ggplot(claydata, aes(x = wall_proximity, fill = treatment)) +
             geom_histogram(position = "identity", alpha = 0.5) +
             labs(title = "Clay Experiment: Wall Proximity",
                  subtitle = "All Proximity Values") +
             xlab("Mean Proximity of Fish to Nearest Wall (cm)") +
             ylab("Counts") +
             scale_fill_manual(values = c("blue", "red", "yellow")) +
             theme_classic()
hist_space <- ggplot(claydata, aes(x = space_use, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Clay Experiment: Space Use",
              subtitle = "All Space Use Values") +
              xlab("Proportion of Space Use") + ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_arrange <- ggarrange(hist_polarity, hist_neighbor, hist_shoal,
                          hist_wall, hist_space, ncol = 3, nrow = 2)


#box plots across all treatments, including all recordings
box_polarity <- claydata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = polarity, fill = treatment)) +
                geom_boxplot() +
                labs(title = "Clay Experiment: Polarity",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Polarity (1-circular variance)") +
                scale_fill_manual(values =
                                  c("slategray1", "wheat1", "wheat4")) +
                ylim(0,1) +
                theme_classic()
box_shoalarea <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = treatment, y = shoal_area, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Shoal Area",
                      subtitle = "Across all recordings") +
                 xlab("Treatments") + ylab("Shoal Area (cm^2)") +
                 scale_fill_manual(values =
                                   c("slategray1", "wheat1", "wheat4")) +
                 ylim(9,75) +
                 theme(plot.title = element_text(size = 16, face = "bold"),
                    plot.subtitle = element_text(size = 15),
                    axis.title = element_text(size = 15, face = "bold"),
                    axis.text = element_text(size = 15),
                    legend.title = element_text(size = 16, face = "bold"),
                    legend.text = element_text(size = 15),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(),
                    axis.line = element_line(),
                    plot.margin = margin(12, 12, 12, 12))
box_neighbor <- claydata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = mean_neighbor,
                           fill = treatment)) +
                geom_boxplot() +
                labs(title = "Clay Experiment: Mean Neighbor Distance",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") +
                scale_fill_manual(values =
                                  c("slategray1", "wheat1", "wheat4")) +
                ylim(6,14) +
                theme_classic()
box_walls <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = wall_proximity,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Wall Proximity",
                   subtitle = "Across all recordings") +
              xlab("Treatments") +
              ylab("Mean Distance to Nearest Wall (cm)") +
              scale_fill_manual(values =
                                c("slategray1", "wheat1", "wheat4")) +
              ylim(0,5) +
              theme(plot.title = element_text(size = 16, face = "bold"),
                    plot.subtitle = element_text(size = 15),
                    axis.title = element_text(size = 15, face = "bold"),
                    axis.text = element_text(size = 15),
                    legend.title = element_text(size = 16, face = "bold"),
                    legend.text = element_text(size = 15),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(),
                    axis.line = element_line(),
                    plot.margin = margin(12, 12, 12, 12))
box_space <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = space_use, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Space Use",
                   subtitle = "Across all recordings") +
              xlab("Treatments") + ylab("Proportion of Space Used") +
              scale_fill_manual(values =
                                c("slategray1", "wheat1", "wheat4")) +
              ylim(0,1) +
              theme_classic()
box_arrange <- ggarrange(box_polarity, box_shoalarea, box_neighbor,
                         box_walls, box_space, ncol = 3, nrow = 2)

#box plots across all treatments, separated by recording
time_polarity <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = polarity, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Polarity",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Polarity (1-circular variance)") + 
                 scale_fill_manual(values =
                                   c("slategray1", "wheat1", "wheat4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                           color = "gray", linewidth = 1.5) +
                 ylim(0,1) +
                 theme_classic()
time_shoalarea <- claydata %>%
                  mutate(treatment = fct_relevel(treatment,
                                                 "clear", "flux", "stable")) %>%
                  ggplot(aes(x = recording, y = shoal_area, fill = treatment)) +
                  geom_boxplot() +
                  labs(title = "Clay Experiment: Mean Shoal Area",
                       subtitle = "All Data by Recording") +
                  xlab("Treatments") + ylab("Shoal Area (cm^2)") + 
                  scale_fill_manual(values =
                                    c("slategray1", "wheat1", "wheat4")) +
                  geom_vline(xintercept = 2.5, linetype = "dashed",
                             color = "gray", linewidth = 1.5) +
                  ylim(9,75) +
                  theme_classic()
time_neighbor <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = mean_neighbor,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Mean Neighbor Distance",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") + 
                 scale_fill_manual(values =
                                   c("slategray1", "wheat1", "wheat4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                            color = "gray", linewidth = 1.5) +
                 ylim(6,14) +
                 theme_classic()
time_walls <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = wall_proximity,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Wall Proximity",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") +
              ylab("Mean Proximity of Fish to Nearest Wall (cm)") + 
              scale_fill_manual(values =
                                c("slategray1", "wheat1", "wheat4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
                         color = "gray", linewidth = 1.5) +
              ylim(0,5) +
              theme_classic()
time_space <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = space_use, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Space Use",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") + ylab("Proportion of Space Used") + 
              scale_fill_manual(values = c("slategray1", "wheat1", "wheat4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
                         color = "gray", linewidth = 1.5) +
              ylim(0,1) +
              theme_classic()
time_arrange <- ggarrange(time_polarity, time_shoalarea, time_neighbor,
                         time_walls, time_space, ncol = 3, nrow = 2)

#boxplots by what visibility level the flux condition was in during the
#recording (high or low)
hilo_polarity <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = polarity, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Polarity",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Polarity (1-circular variance)") +
                 scale_fill_manual(values = c("slategray1", "wheat1",
                                              "wheat4")) +
                 ylim(0,1) +
                 theme_classic()
hilo_shoalarea <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = shoal_area, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Shoal Area",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Shoal Area (cm^2)") +
                 scale_fill_manual(values = c("slategray1", "wheat1",
                                              "wheat4")) +
                 ylim(9,75) +
                 theme_classic()
hilo_neighbor <- claydata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = mean_neighbor,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Clay Experiment: Mean Neighbor Distance",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") +
                 scale_fill_manual(values = c("slategray1", "wheat1",
                                              "wheat4")) +
                 ylim(6,14) +
                 theme_classic()
hilo_walls <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = wall_proximity,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Wall Proximity",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") +
              ylab("Mean Proximity of Fish to Nearest Wall (cm)") +
              scale_fill_manual(values = c("slategray1", "wheat1", "wheat4")) +
              ylim(0,5) +
              theme_classic()
hilo_space <- claydata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = space_use, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Clay Experiment: Space Use",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") + ylab("Proportion of Space Use") +
              scale_fill_manual(values = c("slategray1", "wheat1", "wheat4")) +
              ylim(0,1) +
              theme_classic()
hilo_arrange <- ggarrange(hilo_polarity, hilo_shoalarea, hilo_neighbor,
                         hilo_walls, hilo_space, ncol = 3, nrow = 2)
```


## Dye Plots

```{r dye, echo = FALSE}
#basic histogram plots to look at distributions combining all treatments and all
#recordings
hist_polarity <- ggplot(dyedata, aes(x = polarity, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Dye Experiment: Polarity",
                      subtitle = "All Polarity Values") +
                 xlab("Polarity (1-circular variance)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_neighbor <- ggplot(dyedata, aes(x = mean_neighbor, fill = treatment)) +
                 geom_histogram(position = "identity", alpha = 0.5) +
                 labs(title = "Dye Experiment: Mean Neighbor Distances",
                      subtitle = "All Mean Neighbor Distances") +
                 xlab("Mean Neighbor Distance (cm)") + ylab("Counts") +
                 scale_fill_manual(values = c("blue", "red", "yellow")) +
                 theme_classic()
hist_shoal <- ggplot(dyedata, aes(x = shoal_area, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Dye Experiment: Shoal Area",
                   subtitle = "All Shoal Area Values") +
              xlab("Area of Shoal (cm^2)") + ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_wall <- ggplot(dyedata, aes(x = wall_proximity, fill = treatment)) +
             geom_histogram(position = "identity", alpha = 0.5) +
             labs(title = "Dye Experiment: Wall Proximity",
                  subtitle = "All Proximity Values") +
             xlab("Mean Proximity of Fish to Nearest Wall (cm)") +
             ylab("Counts") +
             scale_fill_manual(values = c("blue", "red", "yellow")) +
             theme_classic()
hist_space <- ggplot(dyedata, aes(x = space_use, fill = treatment)) +
              geom_histogram(position = "identity", alpha = 0.5) +
              labs(title = "Dye Experiment: Space Use",
                   subtitle = "All Space Use Values") +
              xlab("Proportion of Space Use") + ylab("Counts") +
              scale_fill_manual(values = c("blue", "red", "yellow")) +
              theme_classic()
hist_arrange <- ggarrange(hist_polarity, hist_neighbor, hist_shoal,
                          hist_wall, hist_space, ncol = 3, nrow = 2)


#box plots across all treatments, including all recordings
box_polarity <- dyedata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = polarity, fill = treatment)) +
                geom_boxplot() +
                labs(title = "Dye Experiment: Polarity",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Polarity (1-circular variance)") +
                scale_fill_manual(values =
                                  c("slategray1", "snow3", "snow4")) +
                ylim(0,1) +
                theme_classic()
box_shoalarea <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = treatment, y = shoal_area, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Shoal Area",
                      subtitle = "Across all recordings") +
                 xlab("Treatments") + ylab("Shoal Area (cm^2)") +
                 scale_fill_manual(values =
                                   c("slategray1", "snow3", "snow4")) +
                 ylim(9,75) +
                 theme(plot.title = element_text(size = 16, face = "bold"),
                    plot.subtitle = element_text(size = 15),
                    axis.title = element_text(size = 15, face = "bold"),
                    axis.text = element_text(size = 15),
                    legend.title = element_text(size = 16, face = "bold"),
                    legend.text = element_text(size = 15),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(),
                    axis.line = element_line(),
                    plot.margin = margin(12, 12, 12, 12))
box_neighbor <- dyedata %>%
                mutate(treatment = fct_relevel(treatment,
                                               "clear", "flux", "stable")) %>%
                ggplot(aes(x = treatment, y = mean_neighbor,
                           fill = treatment)) +
                geom_boxplot() +
                labs(title = "Dye Experiment: Mean Neighbor Distance",
                     subtitle = "Across all recordings") +
                xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") +
                scale_fill_manual(values =
                                  c("slategray1", "snow3", "snow4")) +
                ylim(6,14) +
                theme_classic()
box_walls <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = wall_proximity,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Wall Proximity",
                   subtitle = "Across all recordings") +
              xlab("Treatments") +
              ylab("Mean Distance to Nearest Wall (cm)") +
              scale_fill_manual(values =
                                c("slategray1", "snow3", "snow4")) +
              ylim(0,5) +
              theme(plot.title = element_text(size = 16, face = "bold"),
                    plot.subtitle = element_text(size = 15),
                    axis.title = element_text(size = 15, face = "bold"),
                    axis.text = element_text(size = 15),
                    legend.title = element_text(size = 16, face = "bold"),
                    legend.text = element_text(size = 15),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(),
                    axis.line = element_line(),
                    plot.margin = margin(12, 12, 12, 12))
box_space <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = treatment, y = space_use, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Space Use",
                   subtitle = "Across all recordings") +
              xlab("Treatments") + ylab("Proportion of Space Used") +
              scale_fill_manual(values =
                                c("slategray1", "snow3", "snow4")) +
              ylim(0,1) +
              theme_classic()
box_arrange <- ggarrange(box_polarity, box_shoalarea, box_neighbor,
                         box_walls, box_space, ncol = 3, nrow = 2)

#box plots across all treatments, separated by recording
time_polarity <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = polarity, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Polarity",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Polarity (1-circular variance)") + 
                 scale_fill_manual(values =
                                   c("slategray1", "snow3", "snow4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                            color = "gray", linewidth = 1.5) +
                 ylim(0,1) +
                 theme_classic()
time_shoalarea <- dyedata %>%
                  mutate(treatment = fct_relevel(treatment,
                                                 "clear", "flux", "stable")) %>%
                  ggplot(aes(x = recording, y = shoal_area, fill = treatment)) +
                  geom_boxplot() +
                  labs(title = "Dye Experiment: Mean Shoal Area",
                       subtitle = "All Data by Recording") +
                  xlab("Treatments") + ylab("Shoal Area (cm^2)") + 
                  scale_fill_manual(values =
                                    c("slategray1", "snow3", "snow4")) +
                  geom_vline(xintercept = 2.5, linetype = "dashed",
                             color = "gray", linewidth = 1.5) +
                  ylim(9,75) +
                  theme_classic()
time_neighbor <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = recording, y = mean_neighbor,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Mean Neighbor Distance",
                      subtitle = "All Data by Recording") +
                 xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") + 
                 scale_fill_manual(values =
                                   c("slategray1", "snow3", "snow4")) +
                 geom_vline(xintercept = 2.5, linetype = "dashed",
                            color = "gray", linewidth = 1.5) +
                 ylim(6,14) +
                 theme_classic()
time_walls <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = wall_proximity,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Wall Proximity",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") +
              ylab("Mean Proximity of Fish to Nearest Wall (cm)") + 
              scale_fill_manual(values =
                                c("slategray1", "snow3", "snow4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
                         color = "gray", linewidth = 1.5) +
              ylim(0,5) +
              theme_classic()
time_space <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = recording, y = space_use, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Space Use",
                   subtitle = "All Data by Recording") +
              xlab("Treatments") + ylab("Proportion of Space Used") + 
              scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
              geom_vline(xintercept = 2.5, linetype = "dashed",
                         color = "gray", linewidth = 1.5) +
              ylim(0,1) +
              theme_classic()
time_arrange <- ggarrange(time_polarity, time_shoalarea, time_neighbor,
                         time_walls, time_space, ncol = 3, nrow = 2)

#boxplots by what visibility level the flux condition was in during the
#recording (high or low)
hilo_polarity <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = polarity, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Polarity",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Polarity (1-circular variance)") +
                 scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
                 ylim(0,1) +
                 theme_classic()
hilo_shoalarea <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = shoal_area, fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Shoal Area",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Shoal Area (cm^2)") +
                 scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
                 ylim(9,75) +
                 theme_classic()
hilo_neighbor <- dyedata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = mean_neighbor,
                            fill = treatment)) +
                 geom_boxplot() +
                 labs(title = "Dye Experiment: Mean Neighbor Distance",
                      subtitle = "All Data by Flux Treatment Visibility") +
                 xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") +
                 scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
                 ylim(6,14) +
                 theme_classic()
hilo_walls <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = wall_proximity,
                         fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Wall Proximity",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") +
              ylab("Mean Proximity of Fish to Nearest Wall (cm)") +
              scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
              ylim(0,5) +
              theme_classic()
hilo_space <- dyedata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = space_use, fill = treatment)) +
              geom_boxplot() +
              labs(title = "Dye Experiment: Space Use",
                   subtitle = "All Data by Flux Treatment Visibility") +
              xlab("Treatments") + ylab("Proportion of Space Use") +
              scale_fill_manual(values = c("slategray1", "snow3", "snow4")) +
              ylim(0,1) +
              theme_classic()
hilo_arrange <- ggarrange(hilo_polarity, hilo_shoalarea, hilo_neighbor,
                         hilo_walls, hilo_space, ncol = 3, nrow = 2)
```


## Combined Plots

```{r combo}
direc_polarity <- combodata %>%
                  filter(recording == "record3") %>%
                  mutate(treatment = fct_relevel(treatment,
                                                 "clear", "flux", "stable")) %>%
                  ggplot(aes(x = flux_level, y = polarity,
                              fill = interaction(experiment, treatment,
                                                 sep = ":"))) +
                  geom_boxplot() +
                  labs(fill = "Experiment:Treatment") +
                  xlab("Treatments") + ylab("Polarity (1-circular variance)") +
                  scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                               "snow3", "wheat4", "snow4")) +
                  ylim(0.35,0.8) +
                  theme_classic()
direc_shoalarea <- combodata %>%
                   filter(recording == "record3") %>%
                   mutate(treatment = fct_relevel(treatment,
                                                  "clear", "flux", "stable")) %>%
                   ggplot(aes(x = flux_level, y = shoal_area,
                              fill = interaction(experiment, treatment,
                                                 sep = ":"))) +
                   geom_boxplot() +
                   labs(fill = "Experiment:Treatment") +
                   xlab("Treatments") + ylab("Shoal Area (cm^2)") +
                   scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                                "snow3", "wheat4", "snow4")) +
                   ylim(9,75) +
                   theme_classic()
direc_neighbor <- combodata %>%
                  filter(recording == "record3") %>%
                  mutate(treatment = fct_relevel(treatment,
                                                 "clear", "flux", "stable")) %>%
                  ggplot(aes(x = flux_level, y = mean_neighbor,
                             fill = interaction(experiment, treatment,
                                               sep = ":"))) +
                  geom_boxplot() +
                  labs(fill = "Experiment:Treatment") +
                  xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") +
                  scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                               "snow3", "wheat4", "snow4")) +
                  ylim(6,14) +
                  theme_classic()
direc_walls <- combodata %>%
               filter(recording == "record3") %>%
               mutate(treatment = fct_relevel(treatment,
                                              "clear", "flux", "stable")) %>%
               ggplot(aes(x = flux_level, y = wall_proximity,
                           fill = interaction(experiment, treatment,
                                              sep = ":"))) +
               geom_boxplot() +
               labs(fill = "Experiment:Treatment") +
               xlab("Treatments") +
               ylab("Mean Proximity of Fish to Nearest Wall (cm)") +
               scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                            "snow3", "wheat4", "snow4")) +
               ylim(1.2,5) +
               theme_classic()
direc_space <- combodata %>%
               filter(recording == "record3") %>%
               mutate(treatment = fct_relevel(treatment,
                                              "clear", "flux", "stable")) %>%
               ggplot(aes(x = flux_level, y = space_use,
                          fill = interaction(experiment, treatment,
                                             sep = ":"))) +
               geom_boxplot() +
               labs(fill = "Experiment:Treatment") +
               xlab("Treatments") + ylab("Proportion of Space Use") +
               scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                            "snow3", "wheat4", "snow4")) +
               ylim(0,1) +
               theme_classic()

hilo_polarity <- combodata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = polarity,
                            fill = interaction(experiment, treatment,
                                               sep = ":"))) +
                 geom_boxplot() +
                 labs(fill = "Experiment:Treatment") +
                 xlab("Treatments") + ylab("Polarity (1-circular variance)") +
                 scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                              "snow3", "wheat4", "snow4")) +
                 ylim(0.35,0.8) +
                 theme_classic()
hilo_shoalarea <- combodata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = shoal_area,
                            fill = interaction(experiment, treatment,
                                               sep = ":"))) +
                 geom_boxplot() +
                 labs(fill = "Experiment:Treatment") +
                 xlab("Treatments") + ylab("Shoal Area (cm^2)") +
                 scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                              "snow3", "wheat4", "snow4")) +
                 ylim(9,75) +
                 theme_classic()
hilo_neighbor <- combodata %>%
                 mutate(treatment = fct_relevel(treatment,
                                                "clear", "flux", "stable")) %>%
                 ggplot(aes(x = flux_level, y = mean_neighbor,
                            fill = interaction(experiment, treatment,
                                               sep = ":"))) +
                 geom_boxplot() +
                 labs(fill = "Experiment:Treatment") +
                 xlab("Treatments") + ylab("Mean Neighbor Distance (cm)") +
                 scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                              "snow3", "wheat4", "snow4")) +
                 ylim(6,14) +
                 theme_classic()
hilo_walls <- combodata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = wall_proximity,
                         fill = interaction(experiment, treatment,
                                            sep = ":"))) +
              geom_boxplot() +
              labs(fill = "Experiment:Treatment") +
              xlab("Treatments") +
              ylab("Mean Proximity of Fish to Nearest Wall (cm)") +
              scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                              "snow3", "wheat4", "snow4")) +
              ylim(1.2,5) +
              theme_classic()
hilo_space <- combodata %>%
              mutate(treatment = fct_relevel(treatment,
                                             "clear", "flux", "stable")) %>%
              ggplot(aes(x = flux_level, y = space_use,
                         fill = interaction(experiment, treatment,
                                            sep = ":"))) +
              geom_boxplot() +
              labs(fill = "Experiment:Treatment") +
              xlab("Treatments") + ylab("Proportion of Space Use") +
              scale_fill_manual(values = c("slategray1", "snow", "wheat1",
                                              "snow3", "wheat4", "snow4")) +
              ylim(0,1) +
              theme_classic()
```